name: cert-manager
namespace: cert-manager
chart:
  source: https://charts.jetstack.io
  name: cert-manager
  version: 1.20.1
values:
  crds:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
  webhook:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 32Mi
  cainjector:
    resources:
      requests:
        cpu: 5m
        memory: 96Mi
      limits:
        memory: 96Mi
