- name: "Provision K3s instance"
  hosts: default
  become: true

  tasks:
    - name: Upgrade apt packages
      apt:
        upgrade: true
        update_cache: true
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
    - name: Configure fail2ban for SSH
      ansible.builtin.copy:
        src: files/fail2ban/sshd.conf
        dest: /etc/fail2ban/jail.d/sshd.conf
    - name: Restart fail2ban
      ansible.builtin.systemd_service:
        state: restarted
        name: fail2ban
    - name: Configure sshd auth
      ansible.builtin.copy:
        src: files/sshd/auth.conf
        dest: /etc/ssh/sshd_config.d/auth.conf
    - name: Disable ufw
      ansible.builtin.command: ufw disable
    - name: Download k3s binary
      ansible.builtin.get_url:
        url: "https://github.com/k3s-io/k3s/releases/download/{{k3s_version}}%2Bk3s1/k3s"
        dest: /usr/local/bin/k3s
        mode: 0755
        owner: 0
        group: 0
    - name: Copy k3s bootstrap script
      ansible.builtin.copy:
        src: files/bootstrap-k3s.sh
        dest: /root/bootstrap-k3s.sh
        mode: 0700
        owner: 0
        group: 0
    - name: Copy OIDC anonymous access manifest
      ansible.builtin.copy:
        src: files/oidc-anonymous-access.yaml
        dest: /root/oidc-anonymous-access.yaml
        mode: 0600
        owner: 0
        group: 0
