hetznerProject: apps-01

kubernetes:
  version: "1.35.3"

hetzner:
  region: nbg1
  sshKeyName: laptop
  secretName: hetzner

controlPlane:
  replicas: 3
  machineType: cx33

workers:
  replicas: 3
  machineType: cx33

podCIDR: "10.244.0.0/16"
