#!/usr/bin/env bash
set -eEuo pipefail

BUCKET="fergalhk-terraform-state"
BUCKET_REGION='eu-west-1'
STATE_KEY_PREFIX="core-infrastructure"
BACKEND_FILE_NAME=__autogenerated_backend.tf

if [[ $# -lt 2 ]]; then
  echo "Usage: ${0} DIRECTORY COMMAND [FLAGS]" >&2
  exit 1
fi

TARGET_DIR="$1"
shift

if [[ ! -d "$TARGET_DIR" ]]; then
  echo "Error: '${TARGET_DIR}' is not a directory" >&2
  exit 1
fi

TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# Derive the state key from the path of TARGET_DIR relative to the git root
GIT_ROOT="$(git -C "$TARGET_DIR" rev-parse --show-toplevel)"

REL_PATH="$(realpath --relative-to="$GIT_ROOT" "$TARGET_DIR")"

if [[ "$REL_PATH" == /* || "$REL_PATH" == ../* ]]; then
  echo "Error: target directory is not inside the git repository" >&2
  exit 1
fi

STATE_KEY="${STATE_KEY_PREFIX}/${REL_PATH}/terraform.tfstate"

echo "Using backend: s3://${BUCKET}/${STATE_KEY}" >&2

cd "$TARGET_DIR"

cat <<EOF > "${BACKEND_FILE_NAME}"
terraform {
  backend "s3" {
    region       = "${BUCKET_REGION}"
    bucket       = "${BUCKET}"
    key          = "${STATE_KEY}"
    use_lockfile = true
  }
}
EOF

exec terraform "$@"
