#!/usr/bin/env bash
set -eEuo pipefail

BUCKET="fergalhk-terraform-state"
BUCKET_REGION='eu-west-1'
ROLE_ARN="arn:aws:iam::740994137039:role/terraform-state-access"
STATE_KEY_PREFIX="core-infrastructure"
BACKEND_FILE_NAME=__autogenerated_backend.tf

if [[ $# -lt 2 ]]; then
  echo "Usage: ${0} DIRECTORY COMMAND [FLAGS]" >&2
  exit 1
fi

TARGET_DIR="$1"
shift

if [[ ! -d "$TARGET_DIR" ]]; then
  echo "Error: '${TARGET_DIR}' is not a directory" >&2
  exit 1
fi

TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# Derive the state key from the path of TARGET_DIR relative to the git root
GIT_ROOT="$(git -C "$TARGET_DIR" rev-parse --show-toplevel)"

REL_PATH="$(realpath --relative-to="$GIT_ROOT" "$TARGET_DIR")"

if [[ "$REL_PATH" == /* || "$REL_PATH" == ../* ]]; then
  echo "Error: target directory is not inside the git repository" >&2
  exit 1
fi

STATE_KEY="${STATE_KEY_PREFIX}/${REL_PATH}/terraform.tfstate"

echo "Using backend: s3://${BUCKET}/${STATE_KEY}" >&2

if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
  echo "GitHub Actions detected — assuming role via OIDC" >&2

  OIDC_TOKEN="$(curl -fsSL \
    -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
    "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
    | jq -r '.value')"

  CREDS="$(aws sts assume-role-with-web-identity \
    --role-arn "${ROLE_ARN}" \
    --role-session-name "github-actions-terraform" \
    --web-identity-token "${OIDC_TOKEN}" \
    --output json)"
else
  echo "Outside GitHub Actions - assuming role via sts:AssumeRole" >&2
  CREDS="$(aws sts assume-role --role-arn "${ROLE_ARN}" --role-session-name terraform)"
fi

S3_AWS_ACCESS_KEY_ID="$(echo "${CREDS}"    | jq -r '.Credentials.AccessKeyId')"
S3_AWS_SECRET_ACCESS_KEY="$(echo "${CREDS}" | jq -r '.Credentials.SecretAccessKey')"
S3_AWS_SESSION_TOKEN="$(echo "${CREDS}"    | jq -r '.Credentials.SessionToken')"

cd "$TARGET_DIR"

cat <<EOF > "${BACKEND_FILE_NAME}"
terraform {
  backend "s3" {
    region       = "${BUCKET_REGION}"
    bucket       = "${BUCKET}"
    key          = "${STATE_KEY}"
    use_lockfile = true
  }
}
EOF

if [ "${1}" == 'init' ];then
  exec terraform \
    "${@}" \
    -backend-config="access_key=${S3_AWS_ACCESS_KEY_ID}" \
    -backend-config="secret_key=${S3_AWS_SECRET_ACCESS_KEY}" \
    -backend-config="token=${S3_AWS_SESSION_TOKEN}"
fi

exec terraform "$@"
