name: cluster-api-operator
namespace: capi-operator-system
chart:
  source: https://kubernetes-sigs.github.io/cluster-api-operator/
  name: cluster-api-operator
  version: 0.26.0
values:
  core:
    cluster-api:
      namespace: capi-system
      version: v1.12.4

  bootstrap:
    kubeadm:
      namespace: capi-kubeadm-bootstrap-system
      version: v1.12.4

  controlPlane:
    kubeadm:
      namespace: capi-kubeadm-control-plane-system
      version: v1.12.4

  infrastructure:
    hetzner:
      namespace: caph-system
      version: v1.0.11

  extraObjects:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: hetzner-token
        namespace: caph-system
      spec:
        refreshInterval: 1h
        secretStoreRef:
          name: aws-secrets-manager
          kind: ClusterSecretStore
        target:
          name: hetzner
          template:
            data:
              hcloud-token: "{{ .hcloud_token }}"
        data:
          - secretKey: hcloud_token
            remoteRef:
              key: apikeys/hetzner/management
