name: external-secrets
namespace: external-secrets
chart:
  source: https://charts.external-secrets.io
  name: external-secrets
  version: 0.10.4
values:
  installCRDs: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
  webhook:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 32Mi
  certController:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 32Mi
  # TODO: refactor to use ClusterSecretStore jwt auth instead of pod-level env vars
  # once a pod mutating webhook is available for true IRSA support
  env:
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::740994137039:role/k8s-mgmt-external-secrets-external-secrets
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
  extraVolumes:
    - name: aws-iam-token
      projected:
        sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
  extraVolumeMounts:
    - name: aws-iam-token
      mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      readOnly: true
  extraObjects:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      metadata:
        name: aws-secrets-manager
      spec:
        provider:
          aws:
            service: SecretsManager
            region: eu-west-1
            role: arn:aws:iam::740994137039:role/k8s-mgmt-external-secrets-external-secrets
