name: external-secrets
namespace: external-secrets
chart:
  source: https://charts.external-secrets.io
  name: external-secrets
  version: 0.10.4
values:
  installCRDs: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
  webhook:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 32Mi
  certController:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 32Mi
  extraObjects:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      metadata:
        name: aws-secrets-manager
      spec:
        provider:
          aws:
            service: SecretsManager
            region: eu-west-1
            role: arn:aws:iam::740994137039:role/k8s-mgmt-external-secrets-external-secrets
            auth:
              jwt:
                serviceAccountRef:
                  name: external-secrets
                  namespace: external-secrets
