name: Reap orphaned packer build servers

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-projects:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.read.outputs.projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Read project names
        id: read
        run: |
          projects=$(yq -o=json -I=0 '.projects | keys' config/hetzner.yaml)
          echo "projects=$projects" >> $GITHUB_OUTPUT

  reap:
    needs: get-projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.get-projects.outputs.projects) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Hetzner token
        id: get-token
        uses: ./.github/actions/get-hcloud-token
        with:
          project_name: ${{ matrix.project }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Delete servers
        env:
          HCLOUD_TOKEN: ${{ steps.get-token.outputs.token }}
        run: go run ./util/reap-orphaned-servers -label-selector 'type=packer-build' -max-age 2h
